#!/usr/bin/env python3
"""Local Integration Agent bridge.

The web data agent is the chat counterpart. This process is intentionally
separate: it makes outbound HTTPS requests to poll for signed work, verifies
each instruction, then writes a reviewable manifest on the local machine.
It never receives a MISO subscription-key value.
"""
import argparse
import hashlib
import hmac
import json
import os
import time
from pathlib import Path
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parent
WEB_URL = os.getenv("WEB_DATA_AGENT_URL", "http://127.0.0.1:8000/api").rstrip("/")
AGENT_ID = os.getenv("LOCAL_AGENT_ID", "default")
TOKEN = os.getenv("LOCAL_AGENT_TOKEN", "development-local-agent-token")
SECRET = os.getenv("LOCAL_AGENT_SHARED_SECRET", "development-only-change-me").encode("utf-8")


def sign(payload):
    body = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hmac.new(SECRET, body, hashlib.sha256).hexdigest()


def request(path, method="GET", payload=None):
    headers = {"Accept": "application/json", "X-Local-Agent-Token": TOKEN}
    body = None
    if payload is not None:
        headers["Content-Type"] = "application/json"
        body = json.dumps(payload).encode("utf-8")
    with urlopen(Request(f"{WEB_URL}{path}", data=body, method=method, headers=headers), timeout=20) as response:
        return json.loads(response.read().decode("utf-8"))


def acknowledge(handoff_id, status, receipt):
    return request("/local-agent/ack/", "POST", {"id": handoff_id, "status": status, "receipt": receipt})


def render_integration_client(handoff_id, payload):
    """Create a generic, reviewable client from a signed catalog instruction.

    The template is deliberately static. Values from the handoff are encoded as
    JSON literals rather than interpolated as Python source, so an endpoint
    label or instruction cannot become executable code.
    """
    endpoint = payload["endpoint"]
    template = '''"""Generated by the MISO Local Integration Agent.

This is a starting point for a reviewed backend integration. It intentionally
reads the subscription key only from the process environment. Do not move the
key into a frontend bundle, source file, or committed .env file.
"""
from __future__ import annotations

import json
import os
from typing import Any, Mapping
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit
from urllib.request import Request, urlopen

HANDOFF_ID = __HANDOFF_ID__
ENDPOINT_ID = __ENDPOINT_ID__
ENDPOINT_NAME = __ENDPOINT_NAME__
METHOD = __METHOD__
DEFAULT_URL = __DEFAULT_URL__
DEFAULT_DATE = __DEFAULT_DATE__
DEFAULT_PARAMETERS = __DEFAULT_PARAMETERS__


def build_url(*, date: str | None = None, parameters: Mapping[str, Any] | None = None) -> str:
    """Build a request URL without exposing or handling credentials."""
    url = DEFAULT_URL
    if "{date}" in url:
        effective_date = date or DEFAULT_DATE
        if not effective_date:
            raise ValueError("This endpoint needs a date in YYYY-MM-DD format.")
        url = url.replace("{date}", effective_date)

    parsed = urlsplit(url)
    query = dict(parse_qsl(parsed.query, keep_blank_values=True))
    query.update({key: str(value) for key, value in DEFAULT_PARAMETERS.items() if value is not None and key != "date"})
    if parameters:
        query.update({key: str(value) for key, value in parameters.items() if value is not None and key != "date"})
    return urlunsplit((parsed.scheme, parsed.netloc, parsed.path, urlencode(query), ""))


class MisoDataExchangeClient:
    """Server-side client for the catalog endpoint in this handoff."""

    def __init__(self, subscription_key: str | None = None, timeout_seconds: int = 20):
        self.subscription_key = subscription_key or os.getenv("MISO_SUBSCRIPTION_KEY")
        self.timeout_seconds = timeout_seconds
        if not self.subscription_key:
            raise RuntimeError("Set MISO_SUBSCRIPTION_KEY in the backend environment before making a live request.")

    def fetch(self, *, date: str | None = None, parameters: Mapping[str, Any] | None = None) -> dict[str, Any]:
        url = build_url(date=date, parameters=parameters)
        request = Request(
            url,
            method=METHOD,
            headers={
                "Accept": "application/json",
                "Ocp-Apim-Subscription-Key": self.subscription_key,
            },
        )
        with urlopen(request, timeout=self.timeout_seconds) as response:
            raw_body = response.read().decode("utf-8")
            return {
                "status_code": response.status,
                "url": url,
                "data": json.loads(raw_body),
            }


if __name__ == "__main__":
    # Run from a backend shell only after MISO_SUBSCRIPTION_KEY is configured.
    try:
        print(MisoDataExchangeClient().fetch())
    except RuntimeError as exc:
        print(json.dumps({"status": "configuration_required", "message": str(exc)}))
        raise SystemExit(2)
'''
    endpoint_url = endpoint["url"]
    default_date = payload.get("parameters", {}).get("date")
    if default_date:
        endpoint_url = endpoint_url.replace(str(default_date), "{date}", 1)
    replacements = {
        "__HANDOFF_ID__": json.dumps(handoff_id),
        "__ENDPOINT_ID__": json.dumps(endpoint["id"]),
        "__ENDPOINT_NAME__": json.dumps(endpoint["name"]),
        "__METHOD__": json.dumps(endpoint["method"]),
        "__DEFAULT_URL__": json.dumps(endpoint_url),
        "__DEFAULT_DATE__": json.dumps(default_date),
        "__DEFAULT_PARAMETERS__": json.dumps(payload.get("parameters", {}), indent=2, sort_keys=True),
    }
    for token, value in replacements.items():
        template = template.replace(token, value)
    return template


def write_applied_integration(handoff_id, payload):
    """Write a new, isolated integration package for explicit --apply runs."""
    target = ROOT / "applied_integrations" / handoff_id
    target.mkdir(parents=True, exist_ok=True)
    client_path = target / "miso_data_exchange_client.py"
    instruction_path = target / "instruction.json"
    readme_path = target / "README.md"
    client_path.write_text(render_integration_client(handoff_id, payload))
    instruction_path.write_text(json.dumps(payload, indent=2) + "\n")

    endpoint = payload["endpoint"]
    troubleshooting = payload.get("troubleshooting")
    readme = f"""# Local MISO integration handoff

Generated from a signature-verified Web Data Agent instruction: `{handoff_id}`.

- Dataset: **{endpoint['name']}** (`{endpoint['id']}`)
- Request: `{endpoint['method']} {endpoint['url']}`
- Credential: read at runtime from `{payload['credential_reference']}` only

## Use it from a backend environment

```bash
export MISO_SUBSCRIPTION_KEY='your-key'
python miso_data_exchange_client.py
```

Review and move the generated client into your backend deliberately. Do not put
the subscription key in browser code, a source file, or version control.
"""
    if troubleshooting:
        readme += f"""
## Troubleshooting context

The web agent supplied an HTTP {troubleshooting['status_code']} diagnosis:
{troubleshooting['suggested_fix']}

`can_retry`: `{troubleshooting['can_retry']}`
"""
    readme_path.write_text(readme)
    return target, (client_path, instruction_path, readme_path)


def process_once(apply=False):
    response = request(f"/local-agent/poll/?agent_id={AGENT_ID}")
    handoff = response.get("handoff")
    if not handoff:
        print("No web-agent instructions waiting.")
        return False
    if not hmac.compare_digest(sign(handoff["payload"]), handoff["signature"]):
        acknowledge(handoff["id"], "failed", {"reason": "Signature validation failed; instruction was not written."})
        raise RuntimeError("Rejected an instruction with an invalid signature.")

    acknowledge(handoff["id"], "received", {"agent_id": AGENT_ID, "message": "Signature verified."})
    target = ROOT / "handoffs" / f"{handoff['id']}.json"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(handoff["payload"], indent=2) + "\n")
    receipt = {
        "agent_id": AGENT_ID,
        "manifest_path": str(target),
        "message": "Instruction written for local review. No source code or credential was changed automatically.",
    }
    if apply:
        generated_directory, generated_files = write_applied_integration(handoff["id"], handoff["payload"])
        receipt = {
            "agent_id": AGENT_ID,
            "manifest_path": str(target),
            "generated_directory": str(generated_directory),
            "generated_files": [str(path) for path in generated_files],
            "message": "Created a reviewable local integration package. No credential was written to disk.",
        }
    acknowledge(
        handoff["id"],
        "completed",
        receipt,
    )
    print(f"Completed handoff {handoff['id']} → {target}")
    return True


def main():
    parser = argparse.ArgumentParser(description="Poll signed work from the MISO web data agent.")
    parser.add_argument("--once", action="store_true", help="Process one queued instruction then exit.")
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Create an isolated, reviewable integration package from a verified instruction.",
    )
    parser.add_argument("--interval", type=float, default=3, help="Polling interval in seconds.")
    args = parser.parse_args()
    if args.once:
        process_once(apply=args.apply)
        return
    while True:
        try:
            process_once(apply=args.apply)
        except Exception as exc:
            print(f"Local agent warning: {exc}")
        time.sleep(max(args.interval, 1))


if __name__ == "__main__":
    main()
