# Generated by Django 6.0.6 on 2026-09-10 04:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miso_agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalAgentHandoff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_id', models.CharField(default='default', max_length=128)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('received', 'received'), ('completed', 'completed'), ('failed', 'failed')], default='queued', max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('signature', models.CharField(max_length=128)),
                ('receipt', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
