/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CanvasRouteImport } from './routes/canvas'
import { Route as IntegrationLabRouteImport } from './routes/integration-lab'
import { Route as PowerTraderRouteImport } from './routes/power-trader'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SubscriptionKeysRouteImport } from './routes/subscription-keys'
import { Route as ApiDocsSourceIdRouteImport } from './routes/api-docs/$sourceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasRoute = CanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationLabRoute = IntegrationLabRouteImport.update({
  id: '/integration-lab',
  path: '/integration-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const PowerTraderRoute = PowerTraderRouteImport.update({
  id: '/power-trader',
  path: '/power-trader',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionKeysRoute = SubscriptionKeysRouteImport.update({
  id: '/subscription-keys',
  path: '/subscription-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsSourceIdRoute = ApiDocsSourceIdRouteImport.update({
  id: '/api-docs/$sourceId',
  path: '/api-docs/$sourceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/canvas': typeof CanvasRoute
  '/integration-lab': typeof IntegrationLabRoute
  '/power-trader': typeof PowerTraderRoute
  '/reports': typeof ReportsRoute
  '/subscription-keys': typeof SubscriptionKeysRoute
  '/api-docs/$sourceId': typeof ApiDocsSourceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/canvas': typeof CanvasRoute
  '/integration-lab': typeof IntegrationLabRoute
  '/power-trader': typeof PowerTraderRoute
  '/reports': typeof ReportsRoute
  '/subscription-keys': typeof SubscriptionKeysRoute
  '/api-docs/$sourceId': typeof ApiDocsSourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/canvas': typeof CanvasRoute
  '/integration-lab': typeof IntegrationLabRoute
  '/power-trader': typeof PowerTraderRoute
  '/reports': typeof ReportsRoute
  '/subscription-keys': typeof SubscriptionKeysRoute
  '/api-docs/$sourceId': typeof ApiDocsSourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/canvas'
    | '/integration-lab'
    | '/power-trader'
    | '/reports'
    | '/subscription-keys'
    | '/api-docs/$sourceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/canvas'
    | '/integration-lab'
    | '/power-trader'
    | '/reports'
    | '/subscription-keys'
    | '/api-docs/$sourceId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/canvas'
    | '/integration-lab'
    | '/power-trader'
    | '/reports'
    | '/subscription-keys'
    | '/api-docs/$sourceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CanvasRoute: typeof CanvasRoute
  IntegrationLabRoute: typeof IntegrationLabRoute
  PowerTraderRoute: typeof PowerTraderRoute
  ReportsRoute: typeof ReportsRoute
  SubscriptionKeysRoute: typeof SubscriptionKeysRoute
  ApiDocsSourceIdRoute: typeof ApiDocsSourceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas': {
      id: '/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof CanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration-lab': {
      id: '/integration-lab'
      path: '/integration-lab'
      fullPath: '/integration-lab'
      preLoaderRoute: typeof IntegrationLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/power-trader': {
      id: '/power-trader'
      path: '/power-trader'
      fullPath: '/power-trader'
      preLoaderRoute: typeof PowerTraderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription-keys': {
      id: '/subscription-keys'
      path: '/subscription-keys'
      fullPath: '/subscription-keys'
      preLoaderRoute: typeof SubscriptionKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs/$sourceId': {
      id: '/api-docs/$sourceId'
      path: '/api-docs/$sourceId'
      fullPath: '/api-docs/$sourceId'
      preLoaderRoute: typeof ApiDocsSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CanvasRoute: CanvasRoute,
  IntegrationLabRoute: IntegrationLabRoute,
  PowerTraderRoute: PowerTraderRoute,
  ReportsRoute: ReportsRoute,
  SubscriptionKeysRoute: SubscriptionKeysRoute,
  ApiDocsSourceIdRoute: ApiDocsSourceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
